### ISSUE TITLE
`resolve_function_symbol` is not suitable

### ISSUE THREAD

**Issue by miquelramirez** [aig-upf/tarski#11]
to account for functional symbols with arity different than 2. The previous iteration included the suffix ```_2``` to indicate that it was the version of the method with 2 parameters. That was not a great solution, as it harks back to the symbol/arity convention of ```Prolog```. Which was a PITA.

```resolve_function_symbol``` needs to refactored so its arguments list is variadic (i.e. using ```*args```).

**Comment by gfrances** [comment]
Miquel, is the current solution with `dispatch_operator` instead of `resolve_function_symbol` satisfactory to you? It's similar to the previous one, but looks like should be enough for our needs? Or do you still see some shortcoming?

**Comment by miquelramirez** [comment]
I think this is an old issue as I do not have any current concerns. 

Thanks for the spring clean of issues.
