### ISSUE TITLE
Match Tree for Action Applicability

### ISSUE THREAD

**Issue by haz** [aig-upf/tarski#117]
### Discussed in https://github.com/aig-upf/tarski/discussions/112

<div type='discussions-op-text'>

<sup>Originally posted by **haz** June  7, 2021</sup>
Any reason this shouldn't be pulled into tarski? It is well-known how much death there can be with the [naive approach](https://github.com/aig-upf/tarski/blob/master/src/tarski/search/model.py#L35). We have a reference implementation both in FD and lapkt (see [here](https://github.com/LAPKT-dev/LAPKT-public/blob/master/interfaces/agnostic/match_tree.hxx) and [here](https://github.com/LAPKT-dev/LAPKT-public/blob/master/interfaces/agnostic/match_tree.cxx)), but I'm not sure this flavour is exactly something that "fits" with the tarski aim (hence a discussion and not an issue).

If not, then a match-tree implementation built on tarski is entirely possible too.

Thoughts?</div>

**Comment by miquelramirez** [comment]
I do not think this is a necessary feature for `tarski`. We never envisioned our classes for representing domain theories and instance data to be readily used in planners. If somebody is interested in providing a Python-based implementation of a component which is critical for the performance of heuristic search methods I am happy to include it for educational purposes.
