### ISSUE TITLE
Atom parsing failes because of whitespace

### ISSUE THREAD

**Issue by phoeft670** [aig-upf/tarski#121]
When parsing .sas files from Fast-Downward parse_atom in utils/helpers.py raises an UndefinedElement error on atoms with arity higher than one, because the whitespace is not ignored.

I will provide a fix on a fork in a few minutes

**Comment by miquelramirez** [comment]
Thank you Paul. I wasn't aware we had a feature for parsing FD's SAS instance data. Will review it as soon as I can and merge into `devel`.

**Comment by miquelramirez** [comment]
Merged into `devel` will get into `master` as soon as we get ready to release `0.7.1`.

Thanks again!
