### ISSUE TITLE
Support for Durative Actions

### ISSUE THREAD

**Issue by karpase** [aig-upf/tarski#129]
I tried parsing a PDDL problem with durative actions, and got a parsing error.
Looks like the K_ACTION only support regular actions, not durative actions, even though DURATIVE_ACTION is still in the list of tokens.

**Comment by miquelramirez** [comment]
Hello @karpase ,

I am reimplementing PDDL support, and I have a mostly working PDDL 2.2 (temporal and axioms) parser in the `devel` branch. I am still working on documentation/examples, and thinking on what kind of API to provide to access the AST and do further processing/transformation/manipulation.

The parser is useable already, you could use it for instance to dump to some intermediate representation that your planner can get the instance data to get cracking.

Regards,

Miquel

**Comment by miquelramirez** [comment]
Also, robust support for exotic things like TILs or variable durations is not an immediate priority to me, but any PRs are welcome.

**Comment by karpase** [comment]
Thanks @miquelramirez, I'll give it a try.

**Comment by miquelramirez** [comment]
Full support of PDDL 2.1 is in principle available in the branch `pddl-2.x-grounding`. Hopefully included in 0.9 release when I get time to put it all together.
