### ISSUE TITLE
Parse PDDL with `oneof`

### ISSUE THREAD

**Issue by hectorpal** [aig-upf/tarski#139]
It would be useful to parse PDDL with `oneof` in:
- `init`: relevant for conformant planning. That would allow to [implement this example in documentation from a conformant PDDL](https://github.com/aig-upf/tarski/blob/devel/docs/notebooks/k0-compilation.ipynb).
- `effects`: relevant for all variants of non-deterministic planning, including FOND.

Are you guys open to that?
What would that entail?

**Comment by hectorpal** [comment]
This discussion is relevant:
https://github.com/aig-upf/tarski/discussions/108#discussioncomment-768694
It was said that extending the parser is hard and suggested to move to [~~Ply~~ Sly](https://github.com/dabeaz/sly).

That would be a lot, of course. I wonder if there is a middle ground.

**Comment by miquelramirez** [comment]
Hi @hectorpal,

we are always open to PRs with new features. The bigger the scope of the changes, the longer it takes to go over them.

Miquel.

**Comment by haz** [comment]
Doesn't quite answer either of the questions :p.

Are you guys no longer doing any active development on the library, or is expanding the input format allowed just not on the roadmap?

**Comment by miquelramirez** [comment]
Yes, it does. 

Honestly @haz I am very tired of these conversations, other "smart" remarks etc. You are wet enough behind the ears to know what the realities of funding in research are. Currently, nobody is willing to put a $ on the table to fund work on providing PDDL modeling support. At least not to us. So Tarski PDDL Consulting Pty Ltd is over.

At the moment, anything that isn't 100% aligned with what I am doing isn't on any roadmaps. If people is interested in new features to be added, they are invited to do so themselves, and I am happy to review and integrate the PR  as my limited time allows.

**Comment by haz** [comment]
This is surprising and devastating news that tarski's no longer accepting public input on things. I don't read @hectorpal 's original questions...

> Are you guys open to that?
> What would that entail?

...as a direct request for implementation. But if there's no room for the community to even engage on how to approach things, then I guess it does sit as a project gone dormant. It truly is a loss for the community, and I say that as one of the first to point people toward the project for anything remotely in-scope. I also understand priorities shift, and it may just not be a burden the tarski co. are willing to shoulder any longer. Thank you to both @gfrances & @miquelramirez for giving it a go -- it's by far the most comprehensive swing for fences on a library the community desperately needs.

**Comment by miquelramirez** [comment]
Thank you for the good vibes, @haz. I appreciate them and I wish there was a funding organisation that accepted them as in-kind contributions.

There is a minimum level of due diligence on behalf community contributions, so they are recognised by my parser. The requirements are summarised in the following checklist:

- [ ]  Identify a gap in the feature set offered
- [ ] Make clear whether the ask is a "feature request" or an "expression of interest" to contribute
- [ ] Articulate the question in terms of the concepts as implemented in the library

Gnomic, over concise statements need more work to progress through the above.

Best,

Miquel

**Comment by miquelramirez** [comment]
Happy to reopen this when/if somebody is interested in implementing support for the PDDL extension for FOND.
