### ISSUE TITLE
Should languages have the EQUALITY theory attached by default?

### ISSUE THREAD

**Issue by miquelramirez** [aig-upf/tarski#24]
Consider the following test case in

https://github.com/aig-upf/tarski/blob/dev-0.2.0/tests/fol/test_interpretations.py

```Python

def test_predicate_extensions2():
    import numpy

    lang = tarski.language(theories=[Theory.EQUALITY])
    leq = lang.predicate('leq', lang.Real, lang.Real)
    w = lang.function('w', lang.Object, lang.Real)
    o1 = lang.constant("o1", lang.Object)
    o2 = lang.constant("o2", lang.Object)

    model = Model(lang)
    model.evaluator = evaluate

    model.setx(w(o1), 1.0)
    model.setx(w(o2), 2.0)
    for x in numpy.arange(0.0, 5.0):
        for y in numpy.arange(x, 5.0):
            model.add(leq, x, y)

    assert model[leq(w(o1), w(o2))] == True
    assert model[leq(w(o2), w(o1))] == False
````

if Theory.EQUALITY is not specified we get an exception when trying to evaluate the formulas

```
leq(w(o1), w(o2))
```

and

```
leq(w(o2), w(o1))
```

The reason for that seems to be that we need the operator == defined for constants which are mappable to integral types. I am not 100% sure why we're not running into issues with arbitrary constants, probably because at some point '==' is being applied over the ```id()``` of the objects?

I tend to think that this is a bug: my understanding of @gfrances design is that one could define all of algebra from first principles... that seems not to be the case.

**Comment by gfrances** [comment]
If I understand correctly, those formulas should fail iff `Theory.ARITHMETIC` is not attached to the language, independently of `Theory.EQUALITY`, right? (i.e. that would be a bug)
Or you mean something different?

**Comment by miquelramirez** [comment]
Those formulas should work fine without need of specifying any extra Theory - there's no fluent or predicate symbols with pre-established meaning.

**Comment by gfrances** [comment]
Oh sorry, I had not seen that you were defining `leq` as a predicate, I thought it was some shorthand that we had for a builtin "<"!
Then you're definitely right, we should not need EQUALITY for this. I'll try to have a look at this tomorrow!

**Comment by gfrances** [comment]
BTW also related to this: we're building all built-in sorts _always_, which I'm not sure is what we want (and perhaps wasn't like this a few months ago, might have introduced that inadvertently). E.g. when defining a language with just the EQUALITY theory, for instance to describe blocksworld, we shouldn't receive a language with the INTEGER, REAL, etc. types defined - right?

**Comment by miquelramirez** [comment]
Built-in sorts have always been included in the language by default since the first commit involving them.

I actually think EQUALITY and the numbers should be default for any language. It doesn't make sense to require people to declare their own sort "MyReals" with the symbols ```"1.0"```, ```"2.0"```, ```"3.0"``` when the language we are using (Python) allows to use directly symbols like ```1.0```, ```2.0```, ```3.0```.

**Comment by gfrances** [comment]
of course, not suggesting that reals, etc dont be builtin, only that they
should perhaps only be "loaded" into the language if explicitly asked so by
the user,  e.g. through the arithmetic theoryor otherwise...

**Comment by miquelramirez** [comment]
Having the builtin Sorts defined doesn't seem to me a burden - asking the user to do so it is as looks like something easy to forget about doing.

I still don't understand exactly why the testcase above fails when EQUALITY isn't loaded (and the == operator is defined) yet doesn't fail for the "named custom object" constants.

**Comment by gfrances** [comment]
BTW, I thought we discussed at some point that it'd be good to version the output of the ANTLR process, i.e. the autogenerated parser files, so that users of the library don't need to have JAVA, ANTLR, etc. installed, but I see that you reverted that in c8311ea739b3183127c2c91ca72237bee9ffb87f ? Wouldn't it be preferable the old behavior, even if of course that means some noise in the git history? Or perhaps some other alternative?

**Comment by gfrances** [comment]
Ok, the culprit is [this line](https://github.com/aig-upf/tarski/blob/f6f2a3b83100e66be48318d23adae99ad5c50ca8/src/tarski/model.py#L118). The `point in dictionary` , where point is `<class 'tuple'>: (1.0 (Real), 2.0 (Real))` relies on the (standard Python) equality and hash functions for e.g. object `Constant(1.0)`, but the (python) equality operator is [overloaded](https://github.com/aig-upf/tarski/blob/efe385e8aba60e626a712ada28192aa48d5e7635/src/tarski/syntax/terms.py#L43) to create logical atoms (!!). Easy to find, but not so easy to fix :-)

**Comment by gfrances** [comment]
The obvious solution would be to use the wrappers you wrote a while ago, right? Or can you think of something better?

**Comment by gfrances** [comment]
Alternative, one could think of giving up on the syntactic sugar nicety of being able to create atoms with `c1 == c2`, etc., and replace that by `eq(c1,c2)` - won't be a disaster, although I like the readability of the first option :-)

**Comment by miquelramirez** [comment]
A more general implementation of ```TermReference``` is ```SymbolReference```, implemented here

https://github.com/aig-upf/tarski/blob/dev-0.2.0/src/tarski/syntax/visitors.py

and which is heavily used by certain transformations (Prenex conversion), grounding and for the automatic rewriting of formulas I have been used to compile planning into SMT etc. Note that syntactic equality can be "naive" or "smart" and try to see through possible variable renamings.

I am not very happy with the implementation for comparing whether two compound terms (or formulae) are the same. What is done at the moment is to force a string conversion and compare the actual "syntactic representation of the two symbols". This turned out to be very efficient.

I avoided to "drill down" via recursion because it is limited by depth (so you can't go over 255 levels of recursive calls, this is an issue when you have big CNF formulas that go well over that number of clauses) and calling methods is very expensive generally in Python.

Still wondering about a better way though.

**Comment by miquelramirez** [comment]
> as there is too much going on in the dev branch

It is the branch where everything is integrated, so it will be messy.

**Comment by gfrances** [comment]
> A more general implementation of `TermReference` is `SymbolReference`

Yup, I saw that, but wasn't sure about what was going on with the string comparisons that you mentioned, and also with the `inclusion_closure`s of the sorts. One thing that you could do to alleviate that recursion problem is to cache the hash value one the object, and compute it in the constructor (given that it won't be modified). Not sure now whether that string `__str__` computation can be triggered upon CompoundTerms; but if it can, then that will trigger a different type of recursion as well. We could as well go with something simpler and add in e.g. `CompoundTerm.__init__`:
```
self.hash = hash((self.symbol.name, tuple(hash(x) for x in subterms)))
```

and then `__hash__` just returns self.hash. That of course won't work if we have different languages with symbols that have the same name, etc., or if in the future we allow two symbols with the same name in the language, but those use cases seem to me too far-fetched at the moment?

**Comment by miquelramirez** [comment]
Done some work to clean up this:

 - ```SymbolReference``` has been refactored away, as the concept of ```TermReference``` you suggested is I think more straightforward
 - Added ```FormulaReference```, the twin of ```TermReference``` and implemented ```is_syntactically_equal``` for all the classes in the ```Formula``` hierarchy

Regarding

> Yup, I saw that, but wasn't sure about what was going on with the string comparisons that you mentioned, and also with the ```inclusion_closure```s of the sorts.

The string comparisons we have discussed already. There's going to be indeed recursion and we can ran afoul of the hardcoded limits anyways.

That had to do with defining two formulas or terms to be equal modulo variable renaming. You can have two sorts with a different name but actually the same domains (including the stuff carried over from its parent). This is (was) useful for grounding, as it allows to "merge" stuff like

```foo(x/A)```

and 

```foo(y/B)```

into one single ```foo(x/A)```, provided that Dom(A)=Dom(B). In cases like that, or

```foo(x/A)```

and 

```foo(y/A)```

which should be collapsed into ```foo(x/A)``` (provided both x and y are free variables, and indeed, grounding requires quantifier elimination in the pipeline). 

In both cases it comes in handy to define differently equality to a reduced significantly the number of candidate expressions involving variables to be grounded.

As an optimization may be useful, but at this stage complicates the implementation quite a bit. And also, the "naive" grounder isn't meant to be optimised, just a fallback when we don't have or don't want to use the soon-to-be ASP grounder.
