### ISSUE TITLE
Explore alternatives to the current ANTLR parser: PLY, SLY

### ISSUE THREAD

**Issue by miquelramirez** [aig-upf/tarski#25]
It just recently came to my attention this Python module

http://www.dabeaz.com/ply/index.html

> PLY is a 100% Python implementation of the common parsing tools lex and yacc.

This looks like a possible alternative to ANTLR - it is both quite mature and seems to be well supported. I haven't looked at how does ```ply``` handle semantic attachments to the parser. This was the prime motivator for me to use ANTLR (that and a cleaner syntax for both the parser and the lexer).

**Comment by gfrances** [comment]
The PLY website mentions that "PLY is currently in maintenance mode only [...]  If you are looking for a parser generator with a more modern flavor, look at the [SLY Project](https://github.com/dabeaz/sly)".
SLY looks really nice. It'd be interesting to know if it improves the performance of the current ANTLR parser - and perhaps we could get rid of one or two segfaults that I'm starting to see with very large PDDL files :-)
I'm not sure I'll have time to delve too deep on this, and there is already some decent amount of work invested in the current ANTLR grammar...

**Comment by miquelramirez** [comment]
Yep, looks like `ply` kicked the bucket. 

`sly` looks good, but I am done with writing parsers for a while. That could definitely be a good third party contribution.
