### ISSUE TITLE
RDDL Support Incoming for both Tarski and FS

### ISSUE THREAD

**Issue by miquelramirez** [aig-upf/tarski#27]
After conferring with Scott Sanner and one of his students (?) Thiago Bueno, I was made aware that there is a fully functional, Python3 ```RDDL``` parser available

https://github.com/miquelramirez/pyrddl

which is ```pip``` installable. Over the next few days I will be mimicking the FSTRIPSWriter/Reader classes so we can work directly on Scott's domains (and use Tarski to produce RDDL models).

**Comment by gfrances** [comment]
Miquel, is this already integrated in the dev branch?

**Comment by miquelramirez** [comment]
Yep, it is all in dev-0.2.0

Miquel

**Comment by gfrances** [comment]
Great, I'll close the issue then!
