### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by miquelramirez** [aig-upf/tarski#28]
I have finished doing a pass over the old Tutorials in the ```notebooks``` folder, and I would need some feedback on them. @gfrances could you take a look through them?

Also, I was wondering if it would be worth the effort to integrate the example with ```pyperplan```, just for the purpose of illustration.

**Comment by gfrances** [comment]
Wow, I keep being impressed over and over again with the kind of things you can do with these jupyter notebooks! Looks very good. I have only some minor comments, but not sure how to change the notebooks myself, to be honest, and test them. It's only 3 or 4 minor things, so I'll paste them below.

What is exactly your idea with pyperplan? Integrate it _within_ Tarski? Have another project "pyperplan-tarski" that integrates both? It'd certainly be a good starting point to add "pedagogical" basic planning capabilities to the language, although perhaps I would opt for creating that in a separate repo? Now that we can manage things with `pip` (e.g. even pointing to a github repo as the source for installation of a package), I think this would not complicate our workflow too much, but would keep things separate... what are your thoughts?


***

002: For Blocks World we can define the function $loc: block \mapsto block$, ... should be block->place

003. Title "Terms, Formulas and Interpretations" should be "Terms and Formulas"
002, 003: Formulas and terms not being printed correctly, e.g. a formula printed as:
<tarski.syntax.formulas.QuantifiedFormula at 0x7f69f0087748>
Did we take away the __str__ methods? I don't remember doing that. What branch is this in?


004: Not sure this TODO still holds?
TODO: Why do we need equality when we have predicates with arguments that are of a builtin Sort?

**Comment by gfrances** [comment]
When I get back from holidays I'll set up a Jupyter server, or however that works, so that I can edit things myself. Looks great!

**Comment by miquelramirez** [comment]
Thanks @gfrances enjoy your holidays. I will be taking a look at ```pyfs``` soon too, we can follow up when you're back.

**Comment by miquelramirez** [comment]
> Section "002" : For Blocks World we can define the function $loc: block \mapsto block$, ... should be block->place

Fixed

> Section "003" Title "Terms, Formulas and Interpretations" should be "Terms and Formulas"

Fixed

> Sections "002", "003": Formulas and terms not being printed correctly, e.g. a formula printed as:
<tarski.syntax.formulas.QuantifiedFormula at 0x7f69f0087748>

The ```str()``` operator is still there and doing its job. What you see there is the actual proper behaviour of the Jupyter notebooks: code cells evaluate the statements in them. So if you write for instance:

```2 + 3```

in a cell, the output is

```5```

Since we were creating an object (or referring an object) what we get as the result is the default ```repr()``` of that object (as above, we get the full qualified class name and the address). 

Your comment made me realise that actually I hadn't reviewed yet Tutorial 3, and the prompts/running text wasn't very useful.

**Comment by miquelramirez** [comment]
> What is exactly your idea with pyperplan? Integrate it within Tarski? Have another project "pyperplan-tarski" that integrates both? 

No, not a formal one. ```pyperplan``` I don't see as a ```proper``` planner, but rather, as a platform to teach about planning.

> It'd certainly be a good starting point to add "pedagogical" basic planning capabilities to the language, although perhaps I would opt for creating that in a separate repo? Now that we can manage things with pip (e.g. even pointing to a github repo as the source for installation of a package), I think this would not complicate our workflow too much, but would keep things separate... what are your thoughts?

The idea was to have a notebook that shows the integration. For that you only need to have ```pyperplan``` installed in your environment. 

This notebook would cover how to construct a simple foward search model from a fully grounded Tarski task, which is then solved with a trivial A* algorithm. Doing that is a fair bit of work, but I think it would also have a very high pedagogical value as it would give practical, reasonably sized examples of how modelling and computation come together (or could come together).

**Comment by gfrances** [comment]
> This notebook would cover how to construct a simple foward search model from a fully grounded Tarski task, which is then solved with a trivial A* algorithm. Doing that is a fair bit of work, but I think it would also have a very high pedagogical value as it would give practical, reasonably sized examples of how modelling and computation come together (or could come together).

Sounds very good. I can help with that if necessary in a couple of weeks, I am reasonably familiar with pyperplan.

**Comment by miquelramirez** [comment]
Still work in progress - will open up new issue as we gather more clear feedback.
