### ISSUE TITLE
FSTRIPS Writer Cannot Handle Term References

### ISSUE THREAD

**Issue by miquelramirez** [aig-upf/tarski#35]
**Problem**:  @emilkeyder is running into trouble using the FSTRIPS printing functions in ```tarski.io.fstrips``` due to ```print_init``` being out of step with the implementation of predicate and function extensions. The issue is that we needed to define as tuples of ```TermReferences``` the entries in the extensions of declared functions and predicates, but the ```print_init``` method is expecting raw terms in lines 88 to 96.

**Proposed fix**: change the calls to ```print_term_list``` to ```print_term_ref_list``` in ```print_init```.

**Comment by gfrances** [comment]
I ran into a similar issue a couple of days, perhaps the method [`list_all_extensions`](https://github.com/aig-upf/tarski/commit/058dfd90a8acdd4273df96e249df07dcf25c7478#diff-d20fbb667e7777d1633d71cf34661fcfR88) that I pushed into the `lite` branch might be of use here? It is not particularly geared towards performance, truth to be told :-)

**Comment by gfrances** [comment]
Ops, you're too fast, Miquel :-)

**Comment by miquelramirez** [comment]
Hi @gfrances - a method like that would probably help simplifying ```print_init``` significantly. In any case, the issue was very localised once I understood @emilkeyder explanation of the problem.
