### ISSUE TITLE
Functional STRIPS with action costs refactorings

### ISSUE THREAD

**Issue by miquelramirez** [aig-upf/tarski#39]
Following up on  the changes proposed by @emilkeyder  on #38 : 

1. There is no need to add specific attributes to ```tarski.fstrips.Problem``` in order to generate domain definitions compatible with IPC planners. I would rather do by adding rules to determine requirements in ```tarski.io._fstrips.common```.  
2. ```IncreaseEffect``` needs to be refactored to avoid complicating the generation of compatible PDDL action effects. We do not need to call the constructor of the super class, we need to ensure that the interface is consistent with the requirements of the type hierarchy. That is, ensure all attributes are defined.
3. The ```ARITHMETIC``` theory is not needed for Parc Printer as we are not using any of the arithmetic operators (i.e. ```+```, etc)

**Comment by miquelramirez** [comment]
Hi @emilkeyder ,

please check out commit https://github.com/aig-upf/tarski/commit/78783266d40923e71e1b59e70d5bc95e870f7a40 and advise if the refactoring still fulfills the original purpose.

Note that I have broken your code, as you don't need to "mark" FSTRIPS problems as using numeric fluents only for the purpose of having action costs.

**Comment by emilkeyder** [comment]
Thanks for integrating this! Changes to my code are just two lines and I've
verified that everything works.

**Comment by miquelramirez** [comment]
Great, I will close this down then.
