### ISSUE TITLE
Provide basic search capabilities

### ISSUE THREAD

**Issue by gfrances** [aig-upf/tarski#45]
One thing that would be really useful for some of my projects would be to have some basic search capabilities integrated into Tarski (doesn't really need to be code that lives within this repo, to be discussed). I think at some point we mentioned with Miquel that an option would be to integrate pyperplan; perhaps that's not even necessary, as most of what pyperplan does in terms of parsing, we already do ourselves. I am just thinking on a basic breadth-first search that lists all reachable states or something along those lines. As a user, I'd like to use Tarski to parse a given (small) instance and then tell it to give me all reachable states, so that I can do cool stuff from them. 

Again, I have this kind-of implemented with Pyperplan, but I would want to do it in a clean and elegant manner with Tarski.

**Comment by miquelramirez** [comment]
This perhaps can be sorted out by providing such a facility as an illustrative example of how one could construct the typical data structures used in search based planners.

**Comment by miquelramirez** [comment]
We already have basic search features available
