### ISSUE TITLE
Implement Some Axiom Inference Algorithm

### ISSUE THREAD

**Issue by gfrances** [aig-upf/tarski#46]
This is a more far fetched project, but I'd like to implement some algorithms (perhaps a good starting point would be Miura & Fukunaga, ICAPS 2017) to infer axioms from the problem description.

**Comment by miquelramirez** [comment]
Deduction of invariants a la DISCOPLAN (or as in the reference above) would require implementation on a close-to-the-metal programming language (or interfacing with an external solver). I would  like to note that  support for the PDDL 3.0 domain constraints concepts mapping onto planning invariants (e.g. logical sentences true in all states) has been provided in the `pddl-2.x-support` branch.
