### ISSUE TITLE
Discuss how to deal with shadowing of Python built-in function names

### ISSUE THREAD

**Issue by gfrances** [aig-upf/tarski#47]
We are currently overriding a few of Python's builtin names with our own function names, namely: `pow`, `min`, `max`, `abs`. I am not in principle against this, but at the same time it is true that I've seen some 

    from blablabla import *

in our code. The conjunction of both things worries me a bit more, since we're opening the door for the user to unadvertently override common functions like `pow`. I understand that it is the responsibility of the user whether to use * imports, but in general we might be sparing the potential users some headaches if we found some workaround for this. What do you think, @miquelramirez ? (a simple possibility would be to rename `pow` to `power`, and similar renamings)

**Comment by miquelramirez** [comment]
Same thing can happen with ```numpy```, if you do a from numpy import * you can expect some trouble. This is usually avoided by using an idiom (like importing ```numpy``` with a short alias). We could potentially promote such an idiom ourselves.

Renaming the functions to avoid name classes I personally think is worse.

**Comment by gfrances** [comment]
Sounds a good option to me, better than what I proposed. Are you ok if I give it a try and replace the global imports

    from blablabla import *

that we ourselves have in our code by something such as 

    import blablabla as bbb

and then of course replace symbols `xxx` by `bbb.xxx` as needed. This should be a relatively safe change to do with the IDE.

**Comment by miquelramirez** [comment]
This sounds good to me, but do not remove global imports from __init.py__, as that is forwarding symbols and I think is a different matter.

**Comment by gfrances** [comment]
Sure!

**Comment by gfrances** [comment]
Turned out there's no such type of `from xxx import *` anymore :-)
