### ISSUE TITLE
Implement Writers and Readers

### ISSUE THREAD

**Issue by gfrances** [aig-upf/tarski#5]
We would like to implement writers and readers in two different formats: json and PDDL. This will definitely help adjust and improve the current code design / API. The code should live under the `tarski.io` module.
Not sure if we want to reuse code from the FS planner and/or FD's python parser, that might be a reasonable first step - what do you think, @miquelramirez ?

**Comment by gfrances** [comment]
I have removed the PDDL io modules, as FSTRIPS subsumes the whole of PDDL, and PDDL problems can be read / written using `tarski.io.fstrips`. As for the `json` io module that we discussed, at the moment I do not have too much use for it, since I am developing `pyfs` to pass all the relevant information through the python bindings, hence doing away with the need of parsing json files, etc.

Do you have other uses for that potential `json` module, Miquel? Otherwise I'd close this issue.

**Comment by miquelramirez** [comment]
That I am afraid was a bit rash @gfrances, could you please coordinate with
@ekeyder and make sure all the functionality has been carried over?

**Comment by gfrances** [comment]
hehe not sure what functionality you meant, I just deleted two empty files! :-)

**Comment by gfrances** [comment]
Relevant commit is here: 15e2fc0

**Comment by miquelramirez** [comment]
So somebody did that already :)

**Comment by gfrances** [comment]
We finally integrated the FS planner with Tarski through a "json" writer, but the json writer is relatively dependent on the hacks and needs of the FS planner, so it lives as an "adapter" in the FS codebase. I don't think there's a need to write a separate, slightly more standard "json" writer here though, as in the mid term we'd like to expose functionality through python bindings. I'll close the issue then.
