### ISSUE TITLE
Implement support for parsing of derived predicates

### ISSUE THREAD

**Issue by gfrances** [aig-upf/tarski#55]
The PDDL / FSTRIPS parser is _mostly_ working, but support for parsing PDDL axioms, aka "derived predicates" is still lacking. 
Related: #12, where we had a long discussion about axioms in Tarski. However, this current issue is a bit different: we just want to be able to parse (and represent) PDDL axioms as defined in the language spec. Seems like that should be simpler.

**Comment by miquelramirez** [comment]
Yep, I agree that as Tarski's scope has got better defined over time #12 is not really a `tarski` issue but a `fs` one.

**Comment by miquelramirez** [comment]
Already implemented in `pddl-2.x-support`
