### ISSUE TITLE
Transformations: Compile function symbols away

### ISSUE THREAD

**Issue by gfrances** [aig-upf/tarski#61]
We'd like to implement a Tarski transformation that takes any basic Functional STRIPS problem and converts it into a plain STRIPS problem (i.e. no function symbols) by applying Patrik Haslum's "Skolemization in reverse" procedure. "Basic" FSTRIPS here means that this should not deal with semantic attachments and other "advanced" FSTRIPS features.

**Comment by miquelramirez** [comment]
This would be useful. What about a SAS backend as well?

**Comment by gfrances** [comment]
Could make a lot of sense to promote the use of FSTRIPS for modeling, and then e.g. transform to SAS and use Fast Downward for solving, if you need the range of capabilities that the planner provides. Will open another "3.0 wishlist" issue for that.

**Comment by gfrances** [comment]
(Not sure if we should compile a Github "project" for that wishlist, instead of a milestone?)

**Comment by miquelramirez** [comment]
The project would allow to prioritise and keep track of progress more clearly. Each of the cards could correspond to a milestone.
