### ISSUE TITLE
Transformations: Project away non-effect variables

### ISSUE THREAD

**Issue by gfrances** [aig-upf/tarski#63]
We'd like to implement a Tarski transformation that takes any STRIPS / Functional STRIPS problem and, for those action schemas that contain parameters (variables) that appear only in the precondition of the schema, but not on the effects, projects this variables into an existentially quantified variable. To illustrate:

    action a(x, y, z)
    PRE: p(x, y) and q(y, z)
    EFF: not p(x, y)

would become:

    action a(x, y)
    PRE: Exists z [p(x, y) and q(y, z)]
    EFF: not p(x, y)

where the action schema has one parameter less.

**Comment by miquelramirez** [comment]
This is an interesting transformation, which is possible to write. Does the LP grounder work with existential precs?

**Comment by gfrances** [comment]
Should work (didn't check though), as long as the existential quantification is in prenex normal form, and not only should it work, it should be significantly more efficient, as e..g will reduce the amount of "ground action" LP atoms that are reachable (if only because the potential number of ground actions decreases). Very good point! An example of a domain with featuring this is the `organic-synthesis` from the last IPC.

**Comment by miquelramirez** [comment]
Maybe a quick test is in order.

**Comment by gfrances** [comment]
This is implemented now, but I'll leave this open a few more days to see if I can test how this plays with the LP grounder.
