### ISSUE TITLE
Remove dependency on scipy

### ISSUE THREAD

**Issue by gfrances** [aig-upf/tarski#7]
The [dependency on scipy](https://github.com/aig-upf/tarski/blob/master/src/tarski/fol.py#L5) should definitely be optional and loaded only when needed. Besides, if the only need we have for it at the moment is defining the symbol Pi, we can probably get rid of it altogether :-)
But surely it'd be better to think on a mechanism for importing it under demand.

**Comment by miquelramirez** [comment]
I have actually changed my mind on this - we need ```scipy``` to represent properly the so-called [Special Functions](https://en.wikipedia.org/wiki/Special_functions) which are now loaded with the theory SPECIAL. 

Following up this, a new theory (RANDOM) will be incoming soon to support representing standard probability distributions so to fully support RDDL1/2.
