### ISSUE TITLE
Error in processing negated preconditions

### ISSUE THREAD

**Issue by anubhav-cs** [aig-upf/tarski#73]
Faced following issue while running some tests on openstacks ipc benchmark problem. 

Error in method `LPGroundingStrategy._solve_lp`:-
1. When negated atoms in action preconditions, for example precondition `(not (made ?p))` in `setup-machine` action causes an error `/tmp/tmp6_w8s8li:676:62-63: error: syntax error, unexpected (`.
2. The content of file `tmp6_w8s8li` at  line `676` is `move(Curpos, Nextpos) :- place(Curpos), place(Nextpos), -None(Curpos), connected(Curpos, Nextpos).`

##### Suggested Fix-  
Issue seems to be arising from line number 200 in `reachability/asp.py`, the `negated` value is `None` in `negated = "-{}".format(negated)`. Hence, a LPAtom with `symbol = -None` is getting created. Changing the line to `negated = "-{}".format(atom.symbol)` seems to be the fix here. Requesting a review.

**Comment by anubhav-cs** [comment]
@gfrances I had a query. How would tarski handle the negated preconditions like `(not (made ?p))`. Currently, I get an [error](https://github.com/anubhav-cs/tarski-tests/blob/master/error.log), where the file [tmp5pun7pck](https://github.com/anubhav-cs/tarski-tests/blob/master/tmp5pun7pck) shows that the rule for `head` - `setup__machine(P, Avail)` has a `-None(P)` lp-atom.

**Comment by gfrances** [comment]
Yes, that appears to be a different issue, give me a couple of hours and I'll look into that as well. Thanks for the report again!

**Comment by gfrances** [comment]
Negated literals in preconditions and goal should no longer be a problem - they are now assumed to be true, as per Helmert, Concise finite-domain representations for PDDL planning tasks, Section 6.1.3.
Let me close this issue and open a new one for the handling of universally-quantified preconditions, which indeed is yet not implemented.
