### ISSUE TITLE
Bug in cnf.py

### ISSUE THREAD

**Issue by anubhav-cs** [aig-upf/tarski#76]
`cnf.py` Devel branch-    

    def to_conjunctive_normal_form(phi, do_copy=True):
        trans = CNFTransformation(phi, do_copy) ---- Issue
        return trans.convert()

    class CNFTransformation:
        def __init__(self, lang, phi, do_copy=True):

*Issue* - In `trans = CNFTransformation(phi, do_copy)` value for `lang` is not passed. Hence, when `CNFTransformation` type `trans` object is created in `to_conjunctive_normal_form`, we get `lang=phi` and `phi = True`

**Comment by gfrances** [comment]
Thanks for the catch! Would you like to create a PR (preferably against the `devel` branch)? If you don't have time don't worry, I can fix this today or tomorrow.

**Comment by anubhav-cs** [comment]
Sure @gfrances

**Comment by gfrances** [comment]
This is fixed now in PR #77
