### ISSUE TITLE
Error while grounding problem and domain with '(:functions ...)'

### ISSUE THREAD

**Issue by anubhav-cs** [aig-upf/tarski#78]
Encountered an error while grounding `ecai-12/scanalyzer` domain problems, when the function `create_reachability_lp` processes the atoms in the `problem.init`. This is specific to the domains where `(:functions (total-cost) - number)` is used and in `init` we have a formula `(= (total-cost) 0)` .  Do I need to transform them? 
The issue can be reproduced by cloning [tarski-test](https://github.com/anubhav-cs/tarski-tests) and running test.py. 
#### Error Log
    Traceback (most recent call last):
      File "test.py", line 166, in <module>
        actions = grounding.ground_actions()
      File "/home/anu/Applications/tarski/src/tarski/grounding/lp_grounding.py", line 39, in ground_actions
        model = self._solve_lp()
      File "/home/anu/Applications/tarski/src/tarski/grounding/lp_grounding.py", line 49, in _solve_lp
    lp, tr = create_reachability_lp(self.problem)
      File "/home/anu/Applications/tarski/src/tarski/reachability/asp.py", line 21, in    create_reachability_lp
        compiler.create()
      File "/home/anu/Applications/tarski/src/tarski/reachability/asp.py", line 54, in create
    assert isinstance(atom, Atom)
    AssertionError

**Comment by gfrances** [comment]
The LP-based component is not ready to deal with functions, but this could certainly be qualified as a bug, we should (1) give a more informative error, and (2) in this particular case of the one only function being the `total-cost` function, which is irrelevant for the reachability analysis, we should simply ignore it. I might be able to fix this later this week, but for the moment being if you need to deal with this problem you could just check for `total-cost` atoms and ignore them, or write a specific routine that removes all such atoms from a problem description (this could probably be helpful in other places in the library).

**Comment by gfrances** [comment]
This should be fixed with the latest changes in devel
