### ISSUE TITLE
Fix Term Evaluation

### ISSUE THREAD

**Issue by gfrances** [aig-upf/tarski#8]
There's currently a subtle but important bug in the [evaluation of constant terms](https://github.com/aig-upf/tarski/blob/master/src/tarski/evaluators/simple.py#L56). The code has some explanations on it, but basically, the denotation of a constant might not always be model-independent. Technically, a constant is a nullary function, and as such, and in a planning context, it won't necessarily have a fixed denotation. A nullary function symbol `looking_at` in blocksworld, for instance, is a constant, although likely it'll be a fluent.

**Comment by miquelramirez** [comment]
Notebooks reviewed and fixed as necessary
