### ISSUE TITLE
Issues introduced by `PySDD` dependency

### ISSUE THREAD

**Issue by miquelramirez** [aig-upf/tarski#81]
I have found a number of issues related to the `PySDD` dependency that got added to the `devel` branch. These are all third-party issues which we cannot do much about.

All of the following are results obtained under `Python 3.6.4` and `pip 19.3.1`:

*Issue no. 1*: There is an ongoing issue with `pip` and binary dependencies that need to be built that prevents from using `pip install --user -e .` on `tarski`. See [this issue](https://github.com/pypa/setuptools/issues/1405#issuecomment-409663455) on `pypa` for details. In order to circumvent this open issue, I had to build `PySDD` first, and then issue the command `pip install --user --no-build-isolation -e .`. 

I presume that if one is working on a virtual environment avoiding this issue will be easier.

*Issue no. 2*: In order to build `PySDD` the package `cysignals` is required. `cysignals` a module for `Cython` that allows accessing hardware interrupt interface. The problem is that in Ubuntu 18.04 `cysignals` is only packaged for `Python 2.x` environments, there's no official package for `Python 3.x`. This can be circumvented working on a virtual environment or installing everything in your local package repository. 

I have added `cysignals` as a dependency for `tarski` as `PySDD` does not include it.

**Comment by gfrances** [comment]
Hi Miquel,

I've also found some other "incompatibilities" with our packaging from the PySDD library, which was breaking our travis builds, as it doesn't seem straightforward to build and install the dependencies correctly. One way to aleviate this could be to install the tarski.sdd module only optionally. In the `setup.py` script you can specify "optional" dependencies that will get installed only if one uses a particular flag when issuing the `pip install tarski` command (don't remember the particular syntax details now, but such an option exists). I'll try to implement that whenever I have a minute later on this week, and check the other issue on grounding as well, sorry for the delay!

**Comment by miquelramirez** [comment]
Hi @gfrances,

I suspected that automated systems like Travis would not like what PySDD does to install itself. One big problem is that the `cysignals` is not packaged for Python 3 in Ubuntu 18. That means that you have to rely on installing both `cython` and `cysignals` via `pip`. Which is not terrible, since official LTS Python packages are usually hopelessly out of date. Maybe is there a way to specify workarounds for `Travis`?

In any case, what you suggest (having this as an optional module) makes perfect sense.

Miquel.

PS: No worries about the grounder bugs. I was looking forward to fix a few of them but they're not so straightforward.

**Comment by gfrances** [comment]
Installing the sdd is now optional, as detailed in the readme.md (see commit 14e1a6d14a7ce334cf4192fefeb9e62902238303 for details). I'll close the issue, but feel free to reopen if necessary!
