### ISSUE TITLE
Rethink builtin symbols

### ISSUE THREAD

**Issue by gfrances** [aig-upf/tarski#9]
I'm starting to think that it might be more elegant to provide a "core language" module and then have all the builtins that we want to provide (perhaps we don't want to provide them monolithically, e.g. the arithmetic function symbols might only be loaded if explicitly required, etc.) separately. I.e. we create a language and then configure it with the "addons" that we want; each addon provides builtin symbols, etc. Both at the syntax and semantic level. To be thought about.

This is somewhat related to issue #6.

**Comment by miquelramirez** [comment]
I think we're quite satisfied for now with our current setup.
