### ISSUE TITLE
Switch from GPLv3 to Apache Software Licence 2.0

### ISSUE THREAD

**Issue by gfrances** [aig-upf/tarski#92]
After some internal and external discussion, and with the agreement of all project contributors, we've decided to switch licence to the Apache Software Licence 2.0. This issue is just to keep track of the change / make it more explicit.

**Comment by gfrances** [comment]
This is now changed in the new release 0.6.0

**Comment by pawamoy** [comment]
Hello! I think you forgot to update the classifier in `setup.py`:

https://github.com/aig-upf/tarski/blob/master/setup.py#L41

I can open a PR to put Apache 2.0 there as well. Then you'd need to push a new release to update the metadata on PyPI, as I'm afraid there's no other way to update it.

**Comment by haz** [comment]
While we're pushing new releases, getting the devel branch out there would be stellar. Always a pain to automate off of a branch.

**Comment by gfrances** [comment]
Thanks @pawamoy , you were totally right. This is fixed in the latest release now.

**Comment by pawamoy** [comment]
Thanks a lot for the quick update @gfrances!
