### ISSUE TITLE
Domain-only parsing

### ISSUE THREAD

**Issue by haz** [aig-upf/tarski#98]
Would be extremely useful to be able to parse just the domain without an associated problem file.

**Comment by gfrances** [comment]
Hi Christian! 

Actually, one thing that I often do in some projects using Tarski is:

```
    reader = FstripsReader()
    reader.parse_domain(domain_file)
    problem = reader.problem
```

Where `problem` now has all of the problem components defined in the domain file alone.
In particular, `problem.language` contains the first-order language defined by the domain,
except of course for the objects that are defined on a per-instance basis.

Would this be enough for your use case?

**Comment by haz** [comment]
Ah, k. So it's a language thing -- the problem object exists, even if it's uninstantiated.

I have more questions, but this would certainly be unrelated to this issue. Can someone one of you enable the chat functionality for this repo so we can have a conversation there on it? Some thoughts may lead to issues, and some may not.

**Comment by gfrances** [comment]
Good to know there's a new chat functionality! Sorry for the delay, Cris, it's enabled now if you want to continue the discussion there.
